/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package General;

import DatabaseManagement.Exceptions.DBManagementException;
import DatabaseManagement.Table;
import SuperAccess.ComboBoxFactory;
import SuperAccess.Form;
import java.util.HashMap;
import SuperAccess.*;
import java.sql.SQLException;

/**
 *
 * @author Dell
 */
public class TableSelector extends javax.swing.JFrame {

    private HashMap<Table, Form> table_to_form;
    private Controller controller;

    public TableSelector() {
        initComponents();
        controller = new Controller();
        ComboBoxFactory.populateTablesCMB(tablesCMB);

        table_to_form = new HashMap<>();
        table_to_form.put(Table.ACCOUNT, new Account());
        table_to_form.put(Table.AIRLINE, new Airline());
        table_to_form.put(Table.AIRPLANE, new Airplane());
        table_to_form.put(Table.AIRPORT, new Airport());
        table_to_form.put(Table.BAGGAGE, new Baggage());
        table_to_form.put(Table.BUSINESS_TICKET, new BusinessTicket());
        table_to_form.put(Table.CITY, new City());
        table_to_form.put(Table.CREWMEMBER, new CrewMember());
        table_to_form.put(Table.ECONOMY_TICKET, new EconomyTicket());
        table_to_form.put(Table.FIRST_TICKET, new FirstTicket());
        table_to_form.put(Table.FLIGHT, new Flight());
        table_to_form.put(Table.GATES, new Gates());
        table_to_form.put(Table.PASSENGER, new Passenger());
        table_to_form.put(Table.PERSON, new Person());
        table_to_form.put(Table.PERSON_FLIGHT, new PersonFlight());
        table_to_form.put(Table.TICKET, new Ticket());
        table_to_form.put(Table.USER_ACTIVITY, new UserActivity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tablesCMB = new javax.swing.JComboBox<>();
        selectTableBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Table");
        setResizable(false);

        TopLabel.setBackground(new java.awt.Color(0, 0, 0));
        TopLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        TopLabel.setForeground(new java.awt.Color(255, 255, 255));
        TopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TopLabel.setText("Select Table");
        TopLabel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablesCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectTableBtn.setBackground(new java.awt.Color(0, 204, 0));
        selectTableBtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        selectTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectTableBtn.setText("Submit");
        selectTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tablesCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectTableBtn)
                        .addGap(160, 160, 160))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tablesCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(selectTableBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTableBtnActionPerformed
        String tableName = tablesCMB.getSelectedItem().toString().trim();
        Table t = Table.valueOf(tableName);
        try {
            new TableViewer(tableName, t, table_to_form.get(t));
        } catch (SQLException ex) {
            controller.displaySQLError(ex);
        } catch (DBManagementException ex) {
            controller.displayErrors("Something went wrong while displaying table names");
        }
    }//GEN-LAST:event_selectTableBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TopLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectTableBtn;
    private javax.swing.JComboBox<String> tablesCMB;
    // End of variables declaration//GEN-END:variables
}
